apiVersion: v1
kind: Pod
metadata:
  name: cuda-check
  namespace: my-gpu-project
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["nvidia-smi"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
        nvidia.com/gpu: 1 # This triggers the injection of CUDA libraries
      limits:
        cpu: 200m
        memory: 256Mi
        nvidia.com/gpu: 1 # This triggers the injection of CUDA libraries
  restartPolicy: Never